pragma Singleton
import Quickshell
import QtQuick

Singleton {
  readonly property color background: "#0e1513"
  readonly property color error: "#ffb4ab"
  readonly property color error_container: "#93000a"
  readonly property color inverse_on_surface: "#2b322f"
  readonly property color inverse_primary: "#0b6b59"
  readonly property color inverse_surface: "#dee4e0"
  readonly property color on_background: "#dee4e0"
  readonly property color on_error: "#690005"
  readonly property color on_error_container: "#ffdad6"
  readonly property color on_primary: "#00382d"
  readonly property color on_primary_container: "#a1f2db"
  readonly property color on_primary_fixed: "#002019"
  readonly property color on_primary_fixed_variant: "#005142"
  readonly property color on_secondary: "#1d352e"
  readonly property color on_secondary_container: "#cde9df"
  readonly property color on_secondary_fixed: "#07201a"
  readonly property color on_secondary_fixed_variant: "#334c44"
  readonly property color on_surface: "#dee4e0"
  readonly property color on_surface_variant: "#bfc9c4"
  readonly property color on_tertiary: "#0f3447"
  readonly property color on_tertiary_container: "#c6e7ff"
  readonly property color on_tertiary_fixed: "#001e2d"
  readonly property color on_tertiary_fixed_variant: "#294a5e"
  readonly property color outline: "#89938f"
  readonly property color outline_variant: "#3f4945"
  readonly property color primary: "#85d6c0"
  readonly property color primary_container: "#005142"
  readonly property color primary_fixed: "#a1f2db"
  readonly property color primary_fixed_dim: "#85d6c0"
  readonly property color scrim: "#000000"
  readonly property color secondary: "#b1ccc3"
  readonly property color secondary_container: "#334c44"
  readonly property color secondary_fixed: "#cde9df"
  readonly property color secondary_fixed_dim: "#b1ccc3"
  readonly property color shadow: "#000000"
  readonly property color surface: "#0e1513"
  readonly property color surface_bright: "#343b38"
  readonly property color surface_container: "#1b211f"
  readonly property color surface_container_high: "#252b29"
  readonly property color surface_container_highest: "#303634"
  readonly property color surface_container_low: "#171d1b"
  readonly property color surface_container_lowest: "#090f0d"
  readonly property color surface_dim: "#0e1513"
  readonly property color surface_tint: "#85d6c0"

  readonly property color surface_variant: "#3f4945"
  readonly property color tertiary: "#a9cbe3"
  readonly property color tertiary_container: "#294a5e"
  readonly property color tertiary_fixed: "#c6e7ff"
  readonly property color tertiary_fixed_dim: "#a9cbe3"

  function withAlpha(color: color, alpha: real): color {
    return Qt.rgba(color.r, color.g, color.b, alpha)
  }
}
