pragma Singleton
import Quickshell
import QtQuick

Singleton {
  readonly property color background: "#0f1511"
  readonly property color error: "#ffb4ab"
  readonly property color error_container: "#93000a"
  readonly property color inverse_on_surface: "#2c322e"
  readonly property color inverse_primary: "#266a4a"
  readonly property color inverse_surface: "#dfe4dd"
  readonly property color on_background: "#dfe4dd"
  readonly property color on_error: "#690005"
  readonly property color on_error_container: "#ffdad6"
  readonly property color on_primary: "#003822"
  readonly property color on_primary_container: "#acf2c8"
  readonly property color on_primary_fixed: "#002112"
  readonly property color on_primary_fixed_variant: "#025233"
  readonly property color on_secondary: "#203529"
  readonly property color on_secondary_container: "#d0e8d7"
  readonly property color on_secondary_fixed: "#0b1f15"
  readonly property color on_secondary_fixed_variant: "#364b3f"
  readonly property color on_surface: "#dfe4dd"
  readonly property color on_surface_variant: "#c0c9c1"
  readonly property color on_tertiary: "#053542"
  readonly property color on_tertiary_container: "#bfe9f9"
  readonly property color on_tertiary_fixed: "#001f28"
  readonly property color on_tertiary_fixed_variant: "#234c59"
  readonly property color outline: "#8a938b"
  readonly property color outline_variant: "#404943"
  readonly property color primary: "#90d5ad"
  readonly property color primary_container: "#025233"
  readonly property color primary_fixed: "#acf2c8"
  readonly property color primary_fixed_dim: "#90d5ad"
  readonly property color scrim: "#000000"
  readonly property color secondary: "#b4ccbb"
  readonly property color secondary_container: "#364b3f"
  readonly property color secondary_fixed: "#d0e8d7"
  readonly property color secondary_fixed_dim: "#b4ccbb"
  readonly property color shadow: "#000000"
  readonly property color surface: "#0f1511"
  readonly property color surface_bright: "#353b36"
  readonly property color surface_container: "#1b211d"
  readonly property color surface_container_high: "#262b27"
  readonly property color surface_container_highest: "#303632"
  readonly property color surface_container_low: "#171d19"
  readonly property color surface_container_lowest: "#0a0f0c"
  readonly property color surface_dim: "#0f1511"
  readonly property color surface_tint: "#90d5ad"

  readonly property color surface_variant: "#404943"
  readonly property color tertiary: "#a4cddd"
  readonly property color tertiary_container: "#234c59"
  readonly property color tertiary_fixed: "#bfe9f9"
  readonly property color tertiary_fixed_dim: "#a4cddd"

  function withAlpha(color: color, alpha: real): color {
    return Qt.rgba(color.r, color.g, color.b, alpha)
  }
}
