# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#121318" # Color de fondo por defecto.
foreground = "#e3e2e9" # Color del texto por defecto.
cursor_bg = "#b2c5ff"
cursor_border = "#c5c6d0"
cursor_fg = "#e3e2e9"

selection_bg = "#151b2c"
selection_fg = "#2a3042"

scrollbar_thumb = "#e3e2e9"  # Color de la barra de desplazamiento.

split = "#45464f" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#b2c5ff",
    "#495d92",
    "#b2c5ff",
    "#e1bbdc",
    "#c0c6dd",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
