# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;{{color0}}\033\\"
printf "\033]4;1;{{color1}}\033\\"
printf "\033]4;2;{{color2}}\033\\"
printf "\033]4;3;{{color3}}\033\\"
printf "\033]4;4;{{color4}}\033\\"
printf "\033]4;5;{{color5}}\033\\"
printf "\033]4;6;{{color6}}\033\\"
printf "\033]4;7;{{color7}}\033\\"
printf "\033]4;8;{{color8}}\033\\"
printf "\033]4;9;{{color9}}\033\\"
printf "\033]4;10;{{color10}}\033\\"
printf "\033]4;11;{{color11}}\033\\"
printf "\033]4;12;{{color12}}\033\\"
printf "\033]4;13;{{color13}}\033\\"
printf "\033]4;14;{{color14}}\033\\"
printf "\033]4;15;{{color15}}\033\\"

# Background
printf "\033]11;{{background}}\033\\";

# Foreground
printf "\033]10;{{foreground}}\033\\";

# Cursor
printf "\033]12;{{cursor}}\033\\";

# Border
printf "\033]7044;{{color1}}\033\\";
