# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

[colors]
background = "#{{background}}" # Color de fondo por defecto.
foreground = "#{{foreground}}" # Color del texto por defecto.
cursor_bg = "#{{cursor}}"
cursor_border = "#{{color12}}"
cursor_fg = "#{{color0}}"

selection_bg = "#{{background}}"
selection_fg = "#{{foreground}}"

scrollbar_thumb = "#{{color12}}" # Color de la barra de desplazamiento.
split = "#{{color7}}" # Color de las líneas de división entre paneles.

ansi = [
    "#{{color0}}",
    "#{{color1}}",
    "#{{color2}}",
    "#{{color3}}",
    "#{{color4}}",
    "#{{color5}}",
    "#{{color6}}",
    "#{{color7}}"
]
brights = [
    "#{{color8}}",
    "#{{color9}}",
    "#{{color10}}",
    "#{{color11}}",
    "#{{color12}}",
    "#{{color13}}",
    "#{{color14}}",
    "#{{color15}}"
]
