[config]
reload_apps = true

[config.wallpaper]
command = "swww"
arguments = [ "img", "-t", "outer", "--transition-duration", "1.5", "--transition-step", "255", "--transition-fps", "60", "-f", "Nearest",]
set = true

[templates.hyprland]
input_path = "./templates/hyprland-colors.conf"
output_path = "../hypr/extra/colors.conf"
post_hook = "hyprctl reload"

[templates.yazi]
input_path = "./templates/yazi-theme.toml"
output_path = "../yazi/theme.toml"

[templates.waybar]
input_path = "./templates/waybar-colors.css"
output_path = "../waybar/waybar-colors.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.rofi]
input_path = "./templates/rofi-colors.rasi"
output_path = "../rofi/rofi-colors.rasi"

[templates.wezterm]
input_path = "./templates/wezterm-colors.toml"
output_path = "../wezterm/colors/wezterm-colors.toml"

[templates.kitty]
input_path = "./templates/kitty-colors.conf"
output_path = "../kitty/kitty-colors.conf"

[templates.foot]
input_path = "./templates/foot-colors.ini"
output_path = "../foot/foot-colors.ini"

[templates.terminal]
input_path = "./templates/terminal.sh"
output_path = "~/.local/bin/terminal.sh"

[templates.variables]
input_path = "./templates/variables.sh"
output_path = "~/.local/bin/variables.sh"

# Volver habilitar syshud
[templates.syshud]
input_path = "./templates/syshud-colors.css"
output_path = "../sys64/hud/syshud-colors.css"

#[templates.obsidian]
#input_path = "./templates/obsidian-theme.css"
#output_path = "~/Obsidian/.obsidian/themes/Walcrow/theme.css"

# Habilitar paletas de web.
#[templates.web]
#input_path = '~/.config/matugen/templates/web-colors.css'
#output_path = '/path/to/startpage/directory'

[templates.ax-shell]
input_path = "~/.config/Ax-Shell/config/matugen/templates/ax-shell.css"
output_path = "~/.config/Ax-Shell/styles/colors.css"
post_hook = "fabric-cli exec ax-shell 'app.set_css()' &"

[config.custom_colors.red]
color = "#FF0000"
blend = true

[config.custom_colors.green]
color = "#00FF00"
blend = true

[config.custom_colors.yellow]
color = "#FFFF00"
blend = true

[config.custom_colors.blue]
color = "#0000FF"
blend = true

[config.custom_colors.magenta]
color = "#FF00FF"
blend = true

[config.custom_colors.cyan]
color = "#00FFFF"
blend = true

[config.custom_colors.white]
color = "#FFFFFF"
blend = true
