[config]
reload_apps = true

[templates.hyprland]
input_path = "./templates/hyprland-colors.conf"
output_path = "../hypr/extra/colors.conf"
post_hook = "hyprctl reload"

[templates.yazi]
input_path = "./templates/yazi-theme.toml"
output_path = "~/.config/yazi/theme.toml"

#[templates.waybar]
#input_path = "./templates/waybar-colors.css"
#output_path = "../waybar/waybar-colors.css"
#post_hook = "pkill -SIGUSR2 waybar"

[templates.quickshell]
input_path = "./templates/quickshell-colors.qml"
output_path = "../quickshell/crow-test/Config/Colors.qml"

[templates.rofi]
input_path = "./templates/rofi-colors.rasi"
output_path = "../rofi/rofi-colors.rasi"

[templates.wezterm]
input_path = "./templates/wezterm-colors.toml"
output_path = ".~/.config/wezterm/colors/wezterm-colors.toml"

[templates.kitty]
input_path = "./templates/kitty-colors.conf"
output_path = "../kitty/kitty-colors.conf"

[templates.foot]
input_path = "./templates/foot-colors.ini"
output_path = "../foot/foot-colors.ini"

[templates.terminal]
input_path = "./templates/terminal.sh"
output_path = "~/.local/bin/terminal.sh"

[templates.variables]
input_path = "./templates/variables.sh"
output_path = "~/.local/bin/variables.sh"

[templates.syshud]
input_path = "./templates/syshud-colors.css"
output_path = "../sys64/hud/syshud-colors.css"

[templates.steam]
input_path = "./templates/AdwSteamGtk-colors.css"
output_path = "../AdwSteamGtk/custom.css"
post_hook = "killall steam"

[templates.gtk3]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = './templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'
