# wallpaper_path = "/home/kh/Wallpapers/space.png"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

[colors]
background = "#000000" # Color de fondo por defecto.
foreground = "#ffccff" # Color del texto por defecto.

cursor_bg = "#ffccff"
cursor_border = "#611f42"
cursor_fg = "#000000"

selection_bg = "#000000"
selection_fg = "#ffccff"

scrollbar_thumb = "#611f42" # Color de la barra de desplazamiento.
split = "#c298c1" # Color de las líneas de división entre paneles.

ansi = [
    "#000000",
    "#1b171e",
    "#231428",
    "#381f2a",
    "#4e1935",
    "#5a294c",
    "#512c4e",
    "#c298c1"
]
brights = [
    "#000303",
    "#211c25",
    "#2b1932",
    "#462634",
    "#611f42",
    "#70335f",
    "#653761",
    "#ffccff"
]