# wallpaper_path = "/home/kh/Wallpapers/platform.jpg"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

[colors]
background = "#0a0b12" # Color de fondo por defecto.
foreground = "#ffffff" # Color del texto por defecto.

cursor_bg = "#ffffff"
cursor_border = "#7b6c78"
cursor_fg = "#0a0b12"

selection_bg = "#0a0b12"
selection_fg = "#ffffff"

scrollbar_thumb = "#7b6c78" # Color de la barra de desplazamiento.
split = "#fee5e0" # Color de las líneas de división entre paneles.

ansi = [
    "#0a0b12",
    "#2e2f46",
    "#3e3f48",
    "#58536b",
    "#635760",
    "#6f708a",
    "#6f718b",
    "#fee5e0"
]
brights = [
    "#2b2e4c",
    "#393a57",
    "#4d4e5a",
    "#6e6785",
    "#7b6c78",
    "#8a8cac",
    "#8a8dad",
    "#ffffff"
]