# wallpaper_path = "/home/kh/Wallpapers/tree.jpg"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

[colors]
background = "#0c0c05" # Color de fondo por defecto.
foreground = "#ffffff" # Color del texto por defecto.

cursor_bg = "#ffffff"
cursor_border = "#b0b094"
cursor_fg = "#0c0c05"

selection_bg = "#0c0c05"
selection_fg = "#ffffff"

scrollbar_thumb = "#b0b094" # Color de la barra de desplazamiento.
split = "#fdfffc" # Color de las líneas de división entre paneles.

ansi = [
    "#0c0c05",
    "#433b10",
    "#4c4d4a",
    "#807461",
    "#8d8d77",
    "#a29c72",
    "#b0b4b0",
    "#fdfffc"
]
brights = [
    "#353315",
    "#534914",
    "#5f605c",
    "#a09179",
    "#b0b094",
    "#cac38e",
    "#dce1dc",
    "#ffffff"
]