# wallpaper_path = "/home/kh/Wallpapers/cabin-5.png"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

[colors]
background = "#040909" # Color de fondo por defecto.
foreground = "#ffeaff" # Color del texto por defecto.

cursor_bg = "#ffeaff"
cursor_border = "#585a7a"
cursor_fg = "#040909"

selection_bg = "#040909"
selection_fg = "#ffeaff"

scrollbar_thumb = "#585a7a" # Color de la barra de desplazamiento.
split = "#d2afd3" # Color de las líneas de división entre paneles.

ansi = [
    "#040909",
    "#22233b",
    "#2d2d36",
    "#303030",
    "#474862",
    "#565763",
    "#775765",
    "#d2afd3"
]
brights = [
    "#142828",
    "#2a2b49",
    "#383843",
    "#3c3c3c",
    "#585a7a",
    "#6b6c7b",
    "#946c7e",
    "#ffeaff"
]