# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#040909\033\\"
printf "\033]4;1;#22233b\033\\"
printf "\033]4;2;#2d2d36\033\\"
printf "\033]4;3;#303030\033\\"
printf "\033]4;4;#474862\033\\"
printf "\033]4;5;#565763\033\\"
printf "\033]4;6;#775765\033\\"
printf "\033]4;7;#d2afd3\033\\"
printf "\033]4;8;#142828\033\\"
printf "\033]4;9;#2a2b49\033\\"
printf "\033]4;10;#383843\033\\"
printf "\033]4;11;#3c3c3c\033\\"
printf "\033]4;12;#585a7a\033\\"
printf "\033]4;13;#6b6c7b\033\\"
printf "\033]4;14;#946c7e\033\\"
printf "\033]4;15;#ffeaff\033\\"

# Background
printf "\033]11;#040909\033\\";

# Foreground
printf "\033]10;#ffeaff\033\\";

# Cursor
printf "\033]12;#ffeaff\033\\";

# Border
printf "\033]7044;#ffeaff\033\\";
