# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#000000\033\\"
printf "\033]4;1;#1b171e\033\\"
printf "\033]4;2;#231428\033\\"
printf "\033]4;3;#381f2a\033\\"
printf "\033]4;4;#4e1935\033\\"
printf "\033]4;5;#5a294c\033\\"
printf "\033]4;6;#512c4e\033\\"
printf "\033]4;7;#c298c1\033\\"
printf "\033]4;8;#000303\033\\"
printf "\033]4;9;#211c25\033\\"
printf "\033]4;10;#2b1932\033\\"
printf "\033]4;11;#462634\033\\"
printf "\033]4;12;#611f42\033\\"
printf "\033]4;13;#70335f\033\\"
printf "\033]4;14;#653761\033\\"
printf "\033]4;15;#ffccff\033\\"

# Background
printf "\033]11;#000000\033\\";

# Foreground
printf "\033]10;#ffccff\033\\";

# Cursor
printf "\033]12;#ffccff\033\\";

# Border
printf "\033]7044;#ffccff\033\\";
