# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#0a0b12\033\\"
printf "\033]4;1;#2e2f46\033\\"
printf "\033]4;2;#3e3f48\033\\"
printf "\033]4;3;#58536b\033\\"
printf "\033]4;4;#635760\033\\"
printf "\033]4;5;#6f708a\033\\"
printf "\033]4;6;#6f718b\033\\"
printf "\033]4;7;#fee5e0\033\\"
printf "\033]4;8;#2b2e4c\033\\"
printf "\033]4;9;#393a57\033\\"
printf "\033]4;10;#4d4e5a\033\\"
printf "\033]4;11;#6e6785\033\\"
printf "\033]4;12;#7b6c78\033\\"
printf "\033]4;13;#8a8cac\033\\"
printf "\033]4;14;#8a8dad\033\\"
printf "\033]4;15;#ffffff\033\\"

# Background
printf "\033]11;#0a0b12\033\\";

# Foreground
printf "\033]10;#ffffff\033\\";

# Cursor
printf "\033]12;#ffffff\033\\";

# Border
printf "\033]7044;#ffffff\033\\";
