# Generated by hellwal

wallpaper='/home/kh/Wallpapers/tree.jpg'

background='0c0c05'
foreground='ffffff'
cursor='ffffff'
border='ffffff'

color0='0c0c05'
color1='433b10'
color2='4c4d4a'
color3='807461'
color4='8d8d77'
color5='a29c72'
color6='b0b4b0'
color7='fdfffc'
color8='353315'
color9='534914'
color10='5f605c'
color11='a09179'
color12='b0b094'
color13='cac38e'
color14='dce1dc'
color15='ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
