# Generated by hellwal

wallpaper='/home/kh/Wallpapers/blueprint.png'

background='090909'
foreground='ffffff'
cursor='ffffff'
border='ffffff'

color0='090909'
color1='203030'
color2='304040'
color3='404050'
color4='454761'
color5='5b5d77'
color6='666873'
color7='ffffff'
color8='282828'
color9='283c3c'
color10='3c5050'
color11='505064'
color12='565879'
color13='717494'
color14='7f828f'
color15='ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
