# Generated by hellwal

wallpaper='/home/kh/Wallpapers/platform.jpg'

background='0a0b12'
foreground='ffffff'
cursor='ffffff'
border='ffffff'

color0='0a0b12'
color1='2e2f46'
color2='3e3f48'
color3='58536b'
color4='635760'
color5='6f708a'
color6='6f718b'
color7='fee5e0'
color8='2b2e4c'
color9='393a57'
color10='4d4e5a'
color11='6e6785'
color12='7b6c78'
color13='8a8cac'
color14='8a8dad'
color15='ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
