# wallpaper_path = "/home/kh/Wallpapers/c1.png"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

[colors]
background = "#0f1721" # Color de fondo por defecto.
foreground = "#fffff0" # Color del texto por defecto.
cursor_bg = "#fffff0"
cursor_border = "#8f899d"
cursor_fg = "#0f1721"

selection_bg = "#0f1721"
selection_fg = "#fffff0"

scrollbar_thumb = "#8f899d" # Color de la barra de desplazamiento.
split = "#e9c1b3" # Color de las líneas de división entre paneles.

ansi = [
    "#0f1721",
    "#46556e",
    "#34698c",
    "#40749b",
    "#736e7e",
    "#76737c",
    "#5f859c",
    "#e9c1b3"
]
brights = [
    "#426289",
    "#576a89",
    "#4183af",
    "#5091c1",
    "#8f899d",
    "#938f9b",
    "#76a6c3",
    "#fffff0"
]
