# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#11140e" # Color de fondo por defecto.
foreground = "#e1e4d9" # Color del texto por defecto.
cursor_bg = "#abd28f"
cursor_border = "#c4c8bb"
cursor_fg = "#e1e4d9"

selection_bg = "#141e0d"
selection_fg = "#283420"

scrollbar_thumb = "#e1e4d9"  # Color de la barra de desplazamiento.

split = "#43483e" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#abd28f",
    "#466730",
    "#abd28f",
    "#a0cfcf",
    "#bdcbaf",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
