# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#0e1514" # Color de fondo por defecto.
foreground = "#dde4e2" # Color del texto por defecto.
cursor_bg = "#80d5cf"
cursor_border = "#bec9c7"
cursor_fg = "#dde4e2"

selection_bg = "#051f1e"
selection_fg = "#1b3533"

scrollbar_thumb = "#dde4e2"  # Color de la barra de desplazamiento.

split = "#3f4948" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#80d5cf",
    "#006a65",
    "#80d5cf",
    "#b0c9e7",
    "#b0ccc9",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
