# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#1a1111" # Color de fondo por defecto.
foreground = "#f0dede" # Color del texto por defecto.
cursor_bg = "#ffb3b6"
cursor_border = "#d7c1c1"
cursor_fg = "#f0dede"

selection_bg = "#2c1516"
selection_fg = "#44292a"

scrollbar_thumb = "#f0dede"  # Color de la barra de desplazamiento.

split = "#524343" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#ffb3b6",
    "#8f4a4e",
    "#ffb3b6",
    "#e6c08d",
    "#e6bdbd",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
