# wallpaper_path = "/home/kh/Wallpapers/kurzgezagt.png"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

[colors]
background = "#06060d" # Color de fondo por defecto.
foreground = "#ffffff" # Color del texto por defecto.
cursor_bg = "#ffffff"
cursor_border = "#837687"
cursor_fg = "#06060d"

selection_bg = "#06060d"
selection_fg = "#ffffff"

scrollbar_thumb = "#837687" # Color de la barra de desplazamiento.
split = "#ffffff" # Color de las líneas de división entre paneles.

ansi = [
    "#06060d",
    "#1d1d24",
    "#393b55",
    "#5e5c78",
    "#695f6c",
    "#a88092",
    "#e4abb2",
    "#ffffff"
]
brights = [
    "#191938",
    "#24242d",
    "#47496a",
    "#757396",
    "#837687",
    "#d2a0b6",
    "#ffd5de",
    "#ffffff"
]
