# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#040406" # Color de fondo por defecto.
foreground = "#575759" # Color del texto por defecto.

cursor_bg = "#C79E88"
cursor_border = "#C79E88"
cursor_fg = "#07070B"

selection_bg = "#C79E88"
selection_fg = "#AEAEB2"

scrollbar_thumb = "#C79E88" # Color de la barra de desplazamiento.

split = "#C79E88" # Color de las líneas de división entre paneles.

ansi = [
    "#38373B",
    "#4D4B56",
    "#93795B",
    "#477E95",
    "#B4637A",
    "#DF8E5E",
    "#D0CDE4",
    "#848389"
]

brights = [
    "#5C5B60",
    "#4D4B56",
    "#93795B",
    "#477E95",
    "#B4637A",
    "#DF8E5E",
    "#D0CDE4",
    "#848389"
]
