# wallpaper_path = "/home/kh/Wallpapers/dino.jpg"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

[colors]
background = "#191921" # Color de fondo por defecto.
foreground = "#ffffff" # Color del texto por defecto.
cursor_bg = "#ffffff"
cursor_border = "#cbb9c5"
cursor_fg = "#191921"

selection_bg = "#191921"
selection_fg = "#ffffff"

scrollbar_thumb = "#cbb9c5" # Color de la barra de desplazamiento.
split = "#efffff" # Color de las líneas de división entre paneles.

ansi = [
    "#191921",
    "#615c73",
    "#91727b",
    "#9f908a",
    "#a3949e",
    "#aeabb8",
    "#debabc",
    "#efffff"
]
brights = [
    "#6b6b8c",
    "#79738f",
    "#b58e99",
    "#c6b4ac",
    "#cbb9c5",
    "#d9d5e6",
    "#ffe8eb",
    "#ffffff"
]
