# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#1a1111" # Color de fondo por defecto.
foreground = "#f1dedd" # Color del texto por defecto.
cursor_bg = "#ffb3af"
cursor_border = "#d8c1c0"
cursor_fg = "#f1dedd"

selection_bg = "#2c1514"
selection_fg = "#442928"

scrollbar_thumb = "#f1dedd"  # Color de la barra de desplazamiento.

split = "#534342" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#ffb3af",
    "#904a47",
    "#ffb3af",
    "#e2c28c",
    "#e7bdba",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
