# wallpaper_path = "/home/kh/Wallpapers/kitchen.png"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

[colors]
background = "#030304" # Color de fondo por defecto.
foreground = "#fff4ff" # Color del texto por defecto.
cursor_bg = "#fff4ff"
cursor_border = "#825c7d"
cursor_fg = "#030304"

selection_bg = "#030304"
selection_fg = "#fff4ff"

scrollbar_thumb = "#825c7d" # Color de la barra de desplazamiento.
split = "#e9b7c6" # Color de las líneas de división entre paneles.

ansi = [
    "#030304",
    "#24243d",
    "#32333d",
    "#3b3c55",
    "#684a64",
    "#646a78",
    "#93748f",
    "#e9b7c6"
]
brights = [
    "#0c0c14",
    "#2d2d4c",
    "#3e3f4c",
    "#494b6a",
    "#825c7d",
    "#7d8496",
    "#b791b2",
    "#fff4ff"
]
