# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#101417" # Color de fondo por defecto.
foreground = "#e0e3e8" # Color del texto por defecto.
cursor_bg = "#95cdf7"
cursor_border = "#c1c7ce"
cursor_fg = "#e0e3e8"

selection_bg = "#0c1d29"
selection_fg = "#22323f"

scrollbar_thumb = "#e0e3e8"  # Color de la barra de desplazamiento.

split = "#41474d" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#95cdf7",
    "#266489",
    "#95cdf7",
    "#cfc0e8",
    "#b7c9d9",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
