# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#030404" # Color de fondo por defecto.
foreground = "#565658" # Color del texto por defecto.

cursor_bg = "#B3B1A8"
cursor_border = "#B3B1A8"
cursor_fg = "#060709"

selection_bg = "#B3B1A8"
selection_fg = "#ACADB0"

scrollbar_thumb = "#B3B1A8" # Color de la barra de desplazamiento.

split = "#B3B1A8" # Color de las líneas de división entre paneles.

ansi = [
    "#2C3535",
    "#484B51",
    "#717785",
    "#AE84A0",
    "#7F94A6",
    "#B9B49F",
    "#96D5D8",
    "#808286"
]

brights = [
    "#5A5B5E",
    "#484B51",
    "#717785",
    "#AE84A0",
    "#7F94A6",
    "#B9B49F",
    "#96D5D8",
    "#808286"
]
