# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#1a1110" # Color de fondo por defecto.
foreground = "#f1dfdc" # Color del texto por defecto.
cursor_bg = "#ffb4a8"
cursor_border = "#d8c2be"
cursor_fg = "#f1dfdc"

selection_bg = "#2c1512"
selection_fg = "#442925"

scrollbar_thumb = "#f1dfdc"  # Color de la barra de desplazamiento.

split = "#534341" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#ffb4a8",
    "#904b40",
    "#ffb4a8",
    "#dec48c",
    "#e7bdb6",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
