# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#15140c" # Color de fondo por defecto.
foreground = "#e7e2d5" # Color del texto por defecto.
cursor_bg = "#d3c972"
cursor_border = "#cbc7b5"
cursor_fg = "#e7e2d5"

selection_bg = "#1f1c05"
selection_fg = "#343117"

scrollbar_thumb = "#e7e2d5"  # Color de la barra de desplazamiento.

split = "#49473a" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#d3c972",
    "#676013",
    "#d3c972",
    "#a6d0b8",
    "#cdc7a3",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
