# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#141318" # Color de fondo por defecto.
foreground = "#e6e1e9" # Color del texto por defecto.
cursor_bg = "#cbbeff"
cursor_border = "#c9c4d0"
cursor_fg = "#e6e1e9"

selection_bg = "#1d192b"
selection_fg = "#322e41"

scrollbar_thumb = "#e6e1e9"  # Color de la barra de desplazamiento.

split = "#48454e" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#cbbeff",
    "#615690",
    "#cbbeff",
    "#eeb8cb",
    "#cac3dc",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
