# wallpaper_path = "/home/kh/Wallpapers/wallpaperflare.com_wallpaper (4).jpg"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

[colors]
background = "#04050b" # Color de fondo por defecto.
foreground = "#ffffff" # Color del texto por defecto.
cursor_bg = "#ffffff"
cursor_border = "#524348"
cursor_fg = "#04050b"

selection_bg = "#04050b"
selection_fg = "#ffffff"

scrollbar_thumb = "#524348" # Color de la barra de desplazamiento.
split = "#dac6c6" # Color de las líneas de división entre paneles.

ansi = [
    "#04050b",
    "#1b1d21",
    "#402b3e",
    "#493233",
    "#42363a",
    "#603b4d",
    "#804143",
    "#dac6c6"
]
brights = [
    "#12172f",
    "#212429",
    "#50354d",
    "#5b3e3f",
    "#524348",
    "#784960",
    "#a05153",
    "#ffffff"
]
