# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#1a1112" # Color de fondo por defecto.
foreground = "#f0dedf" # Color del texto por defecto.
cursor_bg = "#ffb2b8"
cursor_border = "#d7c1c2"
cursor_fg = "#f0dedf"

selection_bg = "#2c1517"
selection_fg = "#44292b"

scrollbar_thumb = "#f0dedf"  # Color de la barra de desplazamiento.

split = "#524344" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#ffb2b8",
    "#8f4951",
    "#ffb2b8",
    "#e8c08e",
    "#e5bdbf",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
