# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#0e1513" # Color de fondo por defecto.
foreground = "#dee4e0" # Color del texto por defecto.
cursor_bg = "#85d6c0"
cursor_border = "#bfc9c4"
cursor_fg = "#dee4e0"

selection_bg = "#07201a"
selection_fg = "#1d352e"

scrollbar_thumb = "#dee4e0"  # Color de la barra de desplazamiento.

split = "#3f4945" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#85d6c0",
    "#0b6b59",
    "#85d6c0",
    "#a9cbe3",
    "#b1ccc3",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
