# wallpaper_path = "/home/kh/Wallpapers/black-hole-1.png"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

[colors]
background = "#070709" # Color de fondo por defecto.
foreground = "#ffffff" # Color del texto por defecto.
cursor_bg = "#ffffff"
cursor_border = "#8d8798"
cursor_fg = "#070709"

selection_bg = "#070709"
selection_fg = "#ffffff"

scrollbar_thumb = "#8d8798" # Color de la barra de desplazamiento.
split = "#fcf0ff" # Color de las líneas de división entre paneles.

ansi = [
    "#070709",
    "#1f1f36",
    "#53556e",
    "#595c78",
    "#716c7a",
    "#76767f",
    "#79878d",
    "#fcf0ff"
]
brights = [
    "#202029",
    "#262643",
    "#676a89",
    "#6f7396",
    "#8d8798",
    "#93939e",
    "#97a8b0",
    "#ffffff"
]
