# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#0f1416" # Color de fondo por defecto.
foreground = "#dee3e6" # Color del texto por defecto.
cursor_bg = "#87d1ea"
cursor_border = "#bfc8cc"
cursor_fg = "#dee3e6"

selection_bg = "#061e25"
selection_fg = "#1d333b"

scrollbar_thumb = "#dee3e6"  # Color de la barra de desplazamiento.

split = "#40484b" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#87d1ea",
    "#02677d",
    "#87d1ea",
    "#c1c4eb",
    "#b3cad4",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
