# wallpaper_path = "/home/kh/Wallpapers/rooftops.jpg"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

[colors]
background = "#0e0f11" # Color de fondo por defecto.
foreground = "#ffffff" # Color del texto por defecto.
cursor_bg = "#ffffff"
cursor_border = "#828492"
cursor_fg = "#0e0f11"

selection_bg = "#0e0f11"
selection_fg = "#ffffff"

scrollbar_thumb = "#828492" # Color de la barra de desplazamiento.
split = "#d9cde4" # Color de las líneas de división entre paneles.

ansi = [
    "#0e0f11",
    "#34454c",
    "#4c4e68",
    "#51546f",
    "#686a75",
    "#868384",
    "#8288a3",
    "#d9cde4"
]
brights = [
    "#3c3e48",
    "#41565f",
    "#5f6182",
    "#65698a",
    "#828492",
    "#a7a3a5",
    "#a2aacb",
    "#ffffff"
]
