# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#101418" # Color de fondo por defecto.
foreground = "#e0e2e8" # Color del texto por defecto.
cursor_bg = "#9ccbfb"
cursor_border = "#c2c7cf"
cursor_fg = "#e0e2e8"

selection_bg = "#0e1d2a"
selection_fg = "#243240"

scrollbar_thumb = "#e0e2e8"  # Color de la barra de desplazamiento.

split = "#42474e" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#9ccbfb",
    "#31628d",
    "#9ccbfb",
    "#d4bee6",
    "#b9c8da",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
