# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#070504" # Color de fondo por defecto.
foreground = "#595656" # Color del texto por defecto.

cursor_bg = "#9A6661"
cursor_border = "#9A6661"
cursor_fg = "#0D0A09"

selection_bg = "#9A6661"
selection_fg = "#B2ABAB"

scrollbar_thumb = "#9A6661" # Color de la barra de desplazamiento.

split = "#9A6661" # Color de las líneas de división entre paneles.

ansi = [
    "#3B302B",
    "#564546",
    "#5C5550",
    "#6F5048",
    "#626050",
    "#9E524B",
    "#786E63",
    "#897F7F"
]

brights = [
    "#605959",
    "#564546",
    "#5C5550",
    "#6F5048",
    "#626050",
    "#9E524B",
    "#786E63",
    "#897F7F"
]
