# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#0A0702" # Color de fondo por defecto.
foreground = "#595454" # Color del texto por defecto.

cursor_bg = "#B97B65"
cursor_border = "#B97B65"
cursor_fg = "#130D05"

selection_bg = "#B97B65"
selection_fg = "#B2A9A7"

scrollbar_thumb = "#B97B65" # Color de la barra de desplazamiento.

split = "#B97B65" # Color de las líneas de división entre paneles.

ansi = [
    "#3B3129",
    "#54413E",
    "#4C5045",
    "#6B5C48",
    "#8C503E",
    "#C75E38",
    "#D9A473",
    "#887C7A"
]

brights = [
    "#5F5655",
    "#54413E",
    "#4C5045",
    "#6B5C48",
    "#8C503E",
    "#C75E38",
    "#D9A473",
    "#887C7A"
]
