# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#131318" # Color de fondo por defecto.
foreground = "#e4e1e9" # Color del texto por defecto.
cursor_bg = "#c0c1ff"
cursor_border = "#c7c5d0"
cursor_fg = "#e4e1e9"

selection_bg = "#191a2c"
selection_fg = "#2e2f42"

scrollbar_thumb = "#e4e1e9"  # Color de la barra de desplazamiento.

split = "#46464f" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#c0c1ff",
    "#575992",
    "#c0c1ff",
    "#e8b9d4",
    "#c5c4dd",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
