# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#141218" # Color de fondo por defecto.
foreground = "#e6e0e9" # Color del texto por defecto.
cursor_bg = "#d0bcfe"
cursor_border = "#cac4cf"
cursor_fg = "#e6e0e9"

selection_bg = "#1e192b"
selection_fg = "#332d41"

scrollbar_thumb = "#e6e0e9"  # Color de la barra de desplazamiento.

split = "#49454e" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#d0bcfe",
    "#65558f",
    "#d0bcfe",
    "#efb8c7",
    "#ccc2db",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
