# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#0e1513" # Color de fondo por defecto.
foreground = "#dee4e1" # Color del texto por defecto.
cursor_bg = "#84d6c3"
cursor_border = "#bec9c5"
cursor_fg = "#dee4e1"

selection_bg = "#06201b"
selection_fg = "#1c352f"

scrollbar_thumb = "#dee4e1"  # Color de la barra de desplazamiento.

split = "#3f4946" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#84d6c3",
    "#046b5c",
    "#84d6c3",
    "#abcae4",
    "#b1ccc4",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
