# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#0e1415" # Color de fondo por defecto.
foreground = "#dde4e3" # Color del texto por defecto.
cursor_bg = "#80d4d6"
cursor_border = "#bec8c8"
cursor_fg = "#dde4e3"

selection_bg = "#041f20"
selection_fg = "#1b3435"

scrollbar_thumb = "#dde4e3"  # Color de la barra de desplazamiento.

split = "#3f4949" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#80d4d6",
    "#00696b",
    "#80d4d6",
    "#b4c8e9",
    "#b0cccc",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
