# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#141318" # Color de fondo por defecto.
foreground = "#e5e1e9" # Color del texto por defecto.
cursor_bg = "#c7bfff"
cursor_border = "#c9c5d0"
cursor_fg = "#e5e1e9"

selection_bg = "#1b192c"
selection_fg = "#312e41"

scrollbar_thumb = "#e5e1e9"  # Color de la barra de desplazamiento.

split = "#47464f" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#c7bfff",
    "#5e5791",
    "#c7bfff",
    "#ecb8ce",
    "#c8c3dc",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
