# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#1a120e" # Color de fondo por defecto.
foreground = "#f0dfd8" # Color del texto por defecto.
cursor_bg = "#ffb691"
cursor_border = "#d7c2b9"
cursor_fg = "#f0dfd8"

selection_bg = "#2b160b"
selection_fg = "#432a1e"

scrollbar_thumb = "#f0dfd8"  # Color de la barra de desplazamiento.

split = "#52443d" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#ffb691",
    "#8d4e2b",
    "#ffb691",
    "#cfc890",
    "#e6beac",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
