# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#14140c" # Color de fondo por defecto.
foreground = "#e6e3d6" # Color del texto por defecto.
cursor_bg = "#cacb77"
cursor_border = "#c9c7b6"
cursor_fg = "#e6e3d6"

selection_bg = "#1c1d06"
selection_fg = "#313219"

scrollbar_thumb = "#e6e3d6"  # Color de la barra de desplazamiento.

split = "#48473a" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#cacb77",
    "#606219",
    "#cacb77",
    "#a4d0be",
    "#c9c8a5",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
