# wallpaper_path = "/home/kh/Wallpapers/whale.jpg"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors

[colors]
background = "#111113" # Color de fondo por defecto.
foreground = "#ffffff" # Color del texto por defecto.
cursor_bg = "#ffffff"
cursor_border = "#8f6f7f"
cursor_fg = "#111113"

selection_bg = "#111113"
selection_fg = "#ffffff"

scrollbar_thumb = "#8f6f7f" # Color de la barra de desplazamiento.
split = "#ffcbe7" # Color de las líneas de división entre paneles.

ansi = [
    "#111113",
    "#373953",
    "#44465f",
    "#5c5e78",
    "#735966",
    "#7f747e",
    "#a88983",
    "#ffcbe7"
]
brights = [
    "#474852",
    "#444767",
    "#555776",
    "#737596",
    "#8f6f7f",
    "#9e919d",
    "#d2aba3",
    "#ffffff"
]
