# wallpaper_path = "%%wallpaper%%"
# REFERENCIA - https://wezfurlong.org/wezterm/config/appearance.html#defining-your-own-colors
# REFERENCIA: https://codeberg.org/explosion-mental/wallust-templates/src/branch/master/wezterm.toml

[colors]
background = "#111318" # Color de fondo por defecto.
foreground = "#e1e2e9" # Color del texto por defecto.
cursor_bg = "#111318"
cursor_border = "#c4c6cf"
cursor_fg = "#e1e2e9"

selection_bg = "#121c2b"
selection_fg = "#273141"

scrollbar_thumb = "#e1e2e9"  # Color de la barra de desplazamiento.

split = "#43474e" # Color de las líneas de división entre paneles.

ansi = [
    "#181818", 
    "#ffb4ab",
    "#a8c8ff",
    "#3f5f90",
    "#a8c8ff",
    "#dbbce1",
    "#bdc7dc",
    "#BAC2DE" 
]

brights = [
    "#585B70",
    "#F38BA8",
    "#A6E3A1",
    "#F9E2AF",
    "#89B4FA",
    "#F5C2E7",
    "#94E2D5",
    "#A6ADC8" 
]
