# Generated by hellwal

wallpaper='{{image}}'

background='{{colors.background.default.hex}}'
foreground='{{colors.on_surface.default.hex}}'
cursor='{{colors.background.default.hex}}'
border='{{colors.on_surface_variant.default.hex}}'

color0='181818'
color1='{{colors.error.default.hex_stripped}}'
color2='{{colors.primary.default.hex_stripped}}'
color3='{{colors.inverse_primary.default.hex_stripped}}'
color4='{{colors.primary.default.hex_stripped}}'
color5='{{colors.tertiary.default.hex_stripped}}'
color6='{{colors.secondary.default.hex_stripped}}'
color7='BAC2DE'

color8='585B70'
color9='F38BA8'
color10='A6E3A1'
color11='F9E2AF'
color12='89B4FA'
color13='F5C2E7'
color14='94E2D5'
color15='A6ADC8'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
