[colors]
# The default text color
foreground = "#dccfd5"
# The default background color
background = "#11181f"

# Overrides the cell background color when the current cell is occupied by the
# cursor and the cursor style is set to Block
cursor_bg = "#dccfd5"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "black"
# Specifies the border color of the cursor when the cursor style is set to Block,
# of the color of the vertical or horizontal bar when the cursor style is set to
# Bar or Underline.
cursor_border = "#52ad70"

# the foreground color of selected text
selection_fg = "black"
# the background color of selected text
selection_bg = "#fffacd"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
scrollbar_thumb = "#222222"

# The color of the split lines between panes
split = "#444444"

ansi = ["#11181f", "#5D5F94", "#43629C", "#9F609C", "#C071B1", "#5F97A5", "#62A6BD", "#dccfd5"]
brights = ["#9a9095", "#5D5F94", "#43629C", "#9F609C", "#C071B1", "#5F97A5", "#62A6BD", "#dccfd5"]

